name: Supabase Keep Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase awake
        run: |
          # Ping REST API
          curl -X GET "${{ secrets.SUPABASE_PROJECT }}/rest/v1/?select=version" \
          -H "apikey: ${{ secrets.SUPABASE_API_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}"
          
          # Ping Auth endpoint
          curl -s "${{ secrets.SUPABASE_PROJECT }}/auth/v1/health"
          
          echo "✅ Supabase keep-alive completed at $(date)"
