name: Supabase Keep Alive
on:
  schedule:
    - cron: "*/5 * * * *"  # runs every 5 minutes to keep Supabase awake

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase awake
        run: curl -s "https://ujbcolxawpzfjkjviwqw.supabase.co"
