name: Supabase Keep Alive

on:
  schedule:
    # Every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows manual testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Auth Health
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_PUBLISHABLE_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}
        run: |
          echo "→ Pinging Supabase Auth at $(date)"
          
          # Ping auth health endpoint
          curl -sS --fail "${SUPABASE_URL}/auth/v1/health" -o /dev/null || {
            echo "❌ Auth health ping failed"
            exit 1
          }
          
          echo "✅ Auth is healthy"
          
      - name: Ping Supabase REST API
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_PUBLISHABLE_KEY: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}
        run: |
          echo "→ Pinging REST API"
          
          # Ping REST API endpoint
          curl -sS --fail \
            -H "apikey: ${SUPABASE_PUBLISHABLE_KEY}" \
            "${SUPABASE_URL}/rest/v1/" -o /dev/null || {
              echo "❌ REST API ping failed"
              exit 1
            }
          
          echo "✅ REST API is responsive"
          
      - name: Completed
        run: echo "✅ Supabase keep-alive completed successfully at $(date)"
