
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ExternalLink, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { useToast } from '@/hooks/use-toast';

interface InsightCardProps {
  icon: React.ReactNode;
  title: string;
  summary: string;
  details: string;
  actions: {
    immediate: string;
    selfManagement: string;
  };
  confidence: 'Low' | 'Medium' | 'High';
  evidenceTag: string;
  borderColor: string;
  bgColor: string;
}

const InsightCard: React.FC<InsightCardProps> = ({
  icon,
  title,
  summary,
  details,
  actions,
  confidence,
  evidenceTag,
  borderColor,
  bgColor,
}) => {
  const { toast } = useToast();
  const confidenceColors = {
    Low: 'bg-orange-100 text-orange-800 border-orange-200',
    Medium: 'bg-blue-100 text-blue-800 border-blue-200',
    High: 'bg-green-100 text-green-800 border-green-200'
  };

  const handleExportForClinician = async () => {
    try {
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const margin = 20;
      let yPosition = 30;

      // Header
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.text('SweatSmart Clinical Insight Report', margin, yPosition);
      yPosition += 15;

      // Date
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Generated: ${format(new Date(), 'EEEE, MMMM d, yyyy')}`, margin, yPosition);
      yPosition += 20;

      // Insight Title
      pdf.setFont('helvetica', 'bold');
      pdf.text(title, margin, yPosition);
      yPosition += 10;

      // Confidence Level
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Confidence Level: ${confidence}`, margin, yPosition);
      yPosition += 8;
      pdf.text(`Evidence: ${evidenceTag}`, margin, yPosition);
      yPosition += 15;

      // Summary
      pdf.setFont('helvetica', 'bold');
      pdf.text('Summary:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      const splitSummary = pdf.splitTextToSize(summary, pageWidth - 2 * margin);
      splitSummary.forEach((line: string) => {
        pdf.text(line, margin, yPosition);
        yPosition += 6;
      });
      yPosition += 10;

      // Details
      pdf.setFont('helvetica', 'bold');
      pdf.text('Clinical Details:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      const splitDetails = pdf.splitTextToSize(details, pageWidth - 2 * margin);
      splitDetails.forEach((line: string) => {
        pdf.text(line, margin, yPosition);
        yPosition += 6;
      });
      yPosition += 10;

      // Recommendations
      pdf.setFont('helvetica', 'bold');
      pdf.text('Immediate Action Recommended:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      const splitImmediate = pdf.splitTextToSize(actions.immediate, pageWidth - 2 * margin);
      splitImmediate.forEach((line: string) => {
        pdf.text(line, margin, yPosition);
        yPosition += 6;
      });
      yPosition += 10;

      pdf.setFont('helvetica', 'bold');
      pdf.text('Self-Management Strategy:', margin, yPosition);
      yPosition += 8;
      pdf.setFont('helvetica', 'normal');
      const splitSelfManagement = pdf.splitTextToSize(actions.selfManagement, pageWidth - 2 * margin);
      splitSelfManagement.forEach((line: string) => {
        pdf.text(line, margin, yPosition);
        yPosition += 6;
      });

      // Footer
      yPosition = pdf.internal.pageSize.getHeight() - 30;
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'italic');
      pdf.text('This report is for clinical reference only. Generated by SweatSmart App.', margin, yPosition);
      pdf.text('Patient should be evaluated clinically before any treatment decisions.', margin, yPosition + 10);

      // Save
      const filename = `sweatsmart-insight-${format(new Date(), 'yyyy-MM-dd')}.pdf`;
      pdf.save(filename);

      toast({
        title: "Clinical report exported",
        description: `Insight report saved as ${filename}`,
      });
    } catch (error) {
      console.error('Error generating clinical report:', error);
      toast({
        title: "Export failed",
        description: "There was an error generating the clinical report. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <Card className={`border-l-4 ${borderColor} ${bgColor}`}>
      <CardHeader className="pb-3">
        <div className="flex items-start justify-between">
          <CardTitle className="flex items-center gap-2 text-lg">
            {icon}
            {title}
          </CardTitle>
          <Badge className={`text-xs ${confidenceColors[confidence]}`}>
            {confidence}
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <p className="text-sm font-medium text-foreground">{summary}</p>
          <p className="text-xs text-muted-foreground">{details}</p>
        </div>
        
        <div className="space-y-2">
          <h4 className="font-medium text-xs text-muted-foreground uppercase tracking-wide">IMMEDIATE ACTION</h4>
          <p className="text-sm bg-green-50 p-3 rounded-lg border-l-4 border-l-green-500 text-green-800">
            {actions.immediate}
          </p>
        </div>
        
        <div className="space-y-2">
          <h4 className="font-medium text-xs text-muted-foreground uppercase tracking-wide">SELF-MANAGEMENT</h4>
          <p className="text-sm bg-blue-50 p-3 rounded-lg border-l-4 border-l-blue-500 text-blue-800">
            {actions.selfManagement}
          </p>
        </div>
        
        <div className="pt-2 border-t space-y-2">
          <p className="text-xs text-muted-foreground">
            Evidence: {evidenceTag}
          </p>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="text-xs">
              <ExternalLink className="h-3 w-3 mr-1" />
              Learn More
            </Button>
            <Button variant="outline" size="sm" className="text-xs" onClick={handleExportForClinician}>
              <Download className="h-3 w-3 mr-1" />
              Export for Clinician
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default InsightCard;
