import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Lightbulb, Stethoscope, Heart, Activity, AlertCircle, Copy, Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';

interface AIInsightsProps {
  insights: {
    clinicalAnalysis: string;
    immediateRelief: string[];
    treatmentOptions: string[];
    lifestyleModifications: string[];
    medicalAttention: string;
  };
}

const AIGeneratedInsights: React.FC<AIInsightsProps> = ({ insights }) => {
  const { toast } = useToast();

  const handleCopyInsights = async () => {
    const insightsText = `
SWEATSMART AI-GENERATED INSIGHTS
=================================

CLINICAL ANALYSIS
${insights.clinicalAnalysis}

IMMEDIATE RELIEF STRATEGIES
${insights.immediateRelief.map((item, i) => `${i + 1}. ${item}`).join('\n\n')}

TREATMENT RECOMMENDATIONS
${insights.treatmentOptions.map((item, i) => `${i + 1}. ${item}`).join('\n\n')}

LIFESTYLE MODIFICATIONS
${insights.lifestyleModifications.map((item, i) => `${i + 1}. ${item}`).join('\n\n')}

WHEN TO SEEK MEDICAL ATTENTION
${insights.medicalAttention}

---
Generated by SweatSmart AI
Disclaimer: These insights are AI-generated and for educational purposes only. Always consult with a healthcare provider for personalized medical advice.
    `.trim();

    try {
      await navigator.clipboard.writeText(insightsText);
      toast({
        title: "Copied to clipboard",
        description: "AI insights have been copied to your clipboard.",
      });
    } catch (error) {
      toast({
        title: "Copy failed",
        description: "Could not copy to clipboard. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 15;
      const maxWidth = pageWidth - (margin * 2);
      let yPosition = 20;

      // Title
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('SweatSmart AI Insights', margin, yPosition);
      yPosition += 10;

      // Disclaimer
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      const disclaimerText = doc.splitTextToSize(
        'These insights are AI-generated for educational purposes only. Always consult with a healthcare provider for personalized medical advice.',
        maxWidth
      );
      doc.text(disclaimerText, margin, yPosition);
      yPosition += disclaimerText.length * 4 + 10;

      // Clinical Analysis
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Clinical Analysis', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const clinicalText = doc.splitTextToSize(insights.clinicalAnalysis, maxWidth);
      doc.text(clinicalText, margin, yPosition);
      yPosition += clinicalText.length * 5 + 10;

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Immediate Relief
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Immediate Relief Strategies', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      insights.immediateRelief.forEach((item, index) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        const itemText = doc.splitTextToSize(`${index + 1}. ${item}`, maxWidth - 5);
        doc.text(itemText, margin + 5, yPosition);
        yPosition += itemText.length * 5 + 5;
      });
      yPosition += 5;

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Treatment Options
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Treatment Recommendations', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      insights.treatmentOptions.forEach((item, index) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        const itemText = doc.splitTextToSize(`${index + 1}. ${item}`, maxWidth - 5);
        doc.text(itemText, margin + 5, yPosition);
        yPosition += itemText.length * 5 + 5;
      });
      yPosition += 5;

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Lifestyle Modifications
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Lifestyle Modifications', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      insights.lifestyleModifications.forEach((item, index) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        const itemText = doc.splitTextToSize(`${index + 1}. ${item}`, maxWidth - 5);
        doc.text(itemText, margin + 5, yPosition);
        yPosition += itemText.length * 5 + 5;
      });
      yPosition += 5;

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Medical Attention
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('When to Seek Medical Attention', margin, yPosition);
      yPosition += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const medicalText = doc.splitTextToSize(insights.medicalAttention, maxWidth);
      doc.text(medicalText, margin, yPosition);

      // Save the PDF
      doc.save(`sweatsmart-insights-${new Date().toISOString().split('T')[0]}.pdf`);

      toast({
        title: "PDF downloaded",
        description: "Your AI insights have been saved as a PDF.",
      });
    } catch (error) {
      console.error('PDF generation error:', error);
      toast({
        title: "Download failed",
        description: "Could not generate PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row gap-3 justify-between items-start sm:items-center">
        <Alert className="border-primary/20 bg-primary/5 flex-1">
          <Stethoscope className="h-4 w-4 text-primary" />
          <AlertDescription>
            These insights are generated by AI trained on hyperhidrosis medical knowledge. Always consult with a healthcare provider for personalized medical advice.
          </AlertDescription>
        </Alert>
        <div className="flex gap-2 w-full sm:w-auto">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopyInsights}
            className="flex-1 sm:flex-none"
          >
            <Copy className="h-4 w-4 mr-2" />
            Copy
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadPDF}
            className="flex-1 sm:flex-none"
          >
            <Download className="h-4 w-4 mr-2" />
            Download
          </Button>
        </div>
      </div>

      {/* Clinical Analysis */}
      <Card className="border-l-4 border-l-blue-500">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Stethoscope className="h-5 w-5 text-blue-600" />
              <CardTitle>Clinical Analysis</CardTitle>
            </div>
            <Badge variant="outline">AI-Generated</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground leading-relaxed">{insights.clinicalAnalysis}</p>
        </CardContent>
      </Card>

      {/* Immediate Relief */}
      <Card className="border-l-4 border-l-green-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Heart className="h-5 w-5 text-green-600" />
            <CardTitle>Immediate Relief Strategies</CardTitle>
          </div>
          <CardDescription>Evidence-based techniques for symptom management</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {insights.immediateRelief.map((strategy, index) => (
              <li key={index} className="flex items-start space-x-2">
                <span className="text-green-600 mt-1">•</span>
                <span className="text-muted-foreground">{strategy}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Treatment Options */}
      <Card className="border-l-4 border-l-purple-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Activity className="h-5 w-5 text-purple-600" />
            <CardTitle>Treatment Recommendations</CardTitle>
          </div>
          <CardDescription>Based on your episode severity and pattern</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {insights.treatmentOptions.map((option, index) => (
              <li key={index} className="flex items-start space-x-2">
                <span className="text-purple-600 mt-1">•</span>
                <span className="text-muted-foreground">{option}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Lifestyle Modifications */}
      <Card className="border-l-4 border-l-orange-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Lightbulb className="h-5 w-5 text-orange-600" />
            <CardTitle>Lifestyle Modifications</CardTitle>
          </div>
          <CardDescription>Actionable changes to reduce episode frequency</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {insights.lifestyleModifications.map((modification, index) => (
              <li key={index} className="flex items-start space-x-2">
                <span className="text-orange-600 mt-1">•</span>
                <span className="text-muted-foreground">{modification}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Medical Attention */}
      <Card className="border-l-4 border-l-red-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <AlertCircle className="h-5 w-5 text-red-600" />
            <CardTitle>When to Seek Medical Attention</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground">{insights.medicalAttention}</p>
        </CardContent>
      </Card>
    </div>
  );
};

export default AIGeneratedInsights;
