import React, { useState, useEffect, useRef } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Lightbulb, Stethoscope, Heart, Activity, AlertCircle, Copy, Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import { cn } from '@/lib/utils';

interface AIInsightsProps {
  insights: {
    clinicalAnalysis: string;
    immediateRelief: string[];
    treatmentOptions: string[];
    lifestyleModifications: string[];
    medicalAttention: string;
    emotionalOpener?: string;
    cta?: string;
  };
}

const AIGeneratedInsights: React.FC<AIInsightsProps> = ({ insights }) => {
  const { toast } = useToast();
  const navigate = useNavigate();
  const [isSpeaking, setIsSpeaking] = useState(false);
  const utteranceRef = useRef<SpeechSynthesisUtterance | null>(null);

  // Cancel speech when component unmounts
  useEffect(() => {
    return () => {
      if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const buildInsightText = () => {
    return [
      insights.emotionalOpener,
      insights.clinicalAnalysis,
      ...(insights.immediateRelief ?? []),
      ...(insights.treatmentOptions ?? []),
      ...(insights.lifestyleModifications ?? []),
      insights.medicalAttention,
    ]
      .filter(Boolean)
      .join('. ');
  };

  const handleToggleSpeak = () => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
      toast({
        title: 'Speech unavailable',
        description: 'Your browser does not support text-to-speech.',
        variant: 'destructive',
      });
      return;
    }

    const synth = window.speechSynthesis;

    // If already speaking — stop
    if (isSpeaking || synth.speaking) {
      synth.cancel();
      setIsSpeaking(false);
      return;
    }

    const text = buildInsightText();
    if (!text.trim()) return;

    const utterance = new SpeechSynthesisUtterance(text);
    utteranceRef.current = utterance;
    utterance.lang = 'en-US';
    utterance.rate = 0.92;
    utterance.pitch = 1.05;
    utterance.volume = 1.0;

    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);
    utterance.onpause = () => setIsSpeaking(false);

    const speak = () => {
      const voices = synth.getVoices();

      if (voices.length === 0) {
        // Voices not loaded yet — wait for voiceschanged
        synth.addEventListener('voiceschanged', () => {
          const v = synth.getVoices();
          const preferred = findBestVoice(v);
          if (preferred) utterance.voice = preferred;
          setIsSpeaking(true);
          synth.speak(utterance);
        }, { once: true });
        return;
      }

      const preferred = findBestVoice(voices);
      if (preferred) utterance.voice = preferred;

      setIsSpeaking(true);
      synth.speak(utterance);

      // Mobile Chrome workaround — sometimes speechSynthesis pauses itself
      // Keep it alive with a heartbeat
      const keepAlive = setInterval(() => {
        if (!synth.speaking) {
          clearInterval(keepAlive);
          setIsSpeaking(false);
          return;
        }
        if (synth.paused) {
          synth.resume();
        }
      }, 5000);

      utterance.onend = () => {
        clearInterval(keepAlive);
        setIsSpeaking(false);
      };
      utterance.onerror = () => {
        clearInterval(keepAlive);
        setIsSpeaking(false);
      };
    };

    speak();
  };

  const findBestVoice = (voices: SpeechSynthesisVoice[]): SpeechSynthesisVoice | null => {
    const preferredNames = [
      'google uk english female',
      'samantha',
      'victoria',
      'karen',
      'aria',
      'zira',
      'hazel',
      'susan',
      'jenny',
    ];
    const englishVoices = voices.filter(v => v.lang.startsWith('en'));
    return (
      englishVoices.find(v =>
        preferredNames.some(k => v.name.toLowerCase().includes(k))
      ) ||
      englishVoices[0] ||
      voices[0] ||
      null
    );
  };

  const handleCopyInsights = async () => {
    const insightsText = `
SWEATSMART AI-GENERATED INSIGHTS
=================================

CLINICAL ANALYSIS
${insights.clinicalAnalysis}

IMMEDIATE RELIEF STRATEGIES
${insights.immediateRelief.map((item, i) => `${i + 1}. ${item}`).join('\n\n')}

TREATMENT RECOMMENDATIONS
${insights.treatmentOptions.map((item, i) => `${i + 1}. ${item}`).join('\n\n')}

LIFESTYLE MODIFICATIONS
${insights.lifestyleModifications.map((item, i) => `${i + 1}. ${item}`).join('\n\n')}

WHEN TO SEEK MEDICAL ATTENTION
${insights.medicalAttention}

---
Generated by SweatSmart AI
Disclaimer: These insights are AI-generated and for educational purposes only. Always consult with a healthcare provider for personalized medical advice.
    `.trim();

    try {
      await navigator.clipboard.writeText(insightsText);
      toast({
        title: 'Copied to clipboard',
        description: 'AI insights have been copied to your clipboard.',
      });
    } catch (error) {
      toast({
        title: 'Copy failed',
        description: 'Could not copy to clipboard. Please try again.',
        variant: 'destructive',
      });
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 15;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      const addSection = (title: string, content: string | string[]) => {
        if (y > 250) { doc.addPage(); y = 20; }
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(title, margin, y);
        y += 7;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const lines = Array.isArray(content)
          ? content.flatMap((item, i) => doc.splitTextToSize(`${i + 1}. ${item}`, maxWidth - 5))
          : doc.splitTextToSize(content, maxWidth);
        lines.forEach((line: string) => {
          if (y > 270) { doc.addPage(); y = 20; }
          doc.text(line, margin + (Array.isArray(content) ? 5 : 0), y);
          y += 5;
        });
        y += 8;
      };

      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('SweatSmart AI Insights', margin, y);
      y += 10;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      const disclaimer = doc.splitTextToSize(
        'These insights are AI-generated for educational purposes only. Always consult with a healthcare provider for personalized medical advice.',
        maxWidth
      );
      doc.text(disclaimer, margin, y);
      y += disclaimer.length * 4 + 10;

      addSection('Clinical Analysis', insights.clinicalAnalysis);
      addSection('Immediate Relief Strategies', insights.immediateRelief);
      addSection('Treatment Recommendations', insights.treatmentOptions);
      addSection('Lifestyle Modifications', insights.lifestyleModifications);
      addSection('When to Seek Medical Attention', insights.medicalAttention);

      doc.save(`sweatsmart-insights-${new Date().toISOString().split('T')[0]}.pdf`);
      toast({ title: 'PDF downloaded', description: 'Your AI insights have been saved as a PDF.' });
    } catch (error) {
      console.error('PDF generation error:', error);
      toast({ title: 'Download failed', description: 'Could not generate PDF. Please try again.', variant: 'destructive' });
    }
  };

  return (
    <div className="space-y-4">
      {/* HidroAlly greeting card */}
      {insights.emotionalOpener && (
        <Card className="border-none bg-gradient-to-br from-violet-500 to-purple-600 text-white shadow-lg overflow-hidden relative">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <Heart className="h-24 w-24 rotate-12" />
          </div>
          <CardHeader className="pb-2">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center backdrop-blur-sm">
                <span className="text-sm">🛡️</span>
              </div>
              <CardTitle className="text-lg font-bold">HidroAlly Analysis</CardTitle>
            </div>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed whitespace-pre-wrap font-medium">
              {insights.emotionalOpener}
            </p>
          </CardContent>
        </Card>
      )}

      {/* Action bar */}
      <div className="flex flex-col sm:flex-row gap-3 justify-between items-start sm:items-center">
        <Alert className="border-primary/20 bg-primary/5 flex-1">
          <Stethoscope className="h-4 w-4 text-primary" />
          <AlertDescription>
            These insights are generated by AI trained on hyperhidrosis knowledge. Always consult a healthcare provider for personal medical advice.
          </AlertDescription>
        </Alert>
        <div className="flex gap-2 w-full sm:w-auto">
          {/* 🔊 Listen / Stop button */}
          <Button
            variant="outline"
            size="sm"
            onClick={handleToggleSpeak}
            className={cn(
              'flex-1 sm:flex-none font-semibold gap-2',
              isSpeaking ? 'bg-primary text-primary-foreground hover:bg-primary/90' : ''
            )}
          >
            <span>{isSpeaking ? '⏹' : '🔊'}</span>
            {isSpeaking ? 'Stop' : 'Listen'}
          </Button>
          <Button variant="outline" size="sm" onClick={handleCopyInsights} className="flex-1 sm:flex-none">
            <Copy className="h-4 w-4 mr-2" /> Copy
          </Button>
          <Button variant="outline" size="sm" onClick={handleDownloadPDF} className="flex-1 sm:flex-none">
            <Download className="h-4 w-4 mr-2" /> Download
          </Button>
        </div>
      </div>

      {/* Clinical Analysis */}
      <Card className="border-l-4 border-l-blue-500">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Stethoscope className="h-5 w-5 text-blue-600" />
              <CardTitle>Clinical Analysis</CardTitle>
            </div>
            <Badge variant="outline">AI-Generated</Badge>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground leading-relaxed">{insights.clinicalAnalysis}</p>
        </CardContent>
      </Card>

      {/* Immediate Relief */}
      <Card className="border-l-4 border-l-green-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Heart className="h-5 w-5 text-green-600" />
            <CardTitle>Immediate Relief Strategies</CardTitle>
          </div>
          <CardDescription>Evidence-based techniques for symptom management</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {insights.immediateRelief.map((strategy, index) => (
              <li key={index} className="flex gap-3">
                <span className="text-primary mt-1 flex-shrink-0">•</span>
                <span className="text-muted-foreground">{strategy}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Treatment Options */}
      <Card className="border-l-4 border-l-purple-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Activity className="h-5 w-5 text-purple-600" />
            <CardTitle>Treatment Recommendations</CardTitle>
          </div>
          <CardDescription>Based on your episode severity and pattern</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {insights.treatmentOptions.map((option, index) => (
              <li key={index} className="flex gap-3">
                <span className="text-primary mt-1 flex-shrink-0">•</span>
                <span className="text-muted-foreground">{option}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Lifestyle Modifications */}
      <Card className="border-l-4 border-l-orange-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <Lightbulb className="h-5 w-5 text-orange-600" />
            <CardTitle>Lifestyle Modifications</CardTitle>
          </div>
          <CardDescription>Actionable changes to reduce episode frequency</CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-3">
            {insights.lifestyleModifications.map((modification, index) => (
              <li key={index} className="flex gap-3">
                <span className="text-primary mt-1 flex-shrink-0">•</span>
                <span className="text-muted-foreground">{modification}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* When to seek help */}
      <Card className="border-l-4 border-l-red-500">
        <CardHeader>
          <div className="flex items-center space-x-2">
            <AlertCircle className="h-5 w-5 text-red-600" />
            <CardTitle>When to Seek Medical Attention</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground">{insights.medicalAttention}</p>
        </CardContent>
      </Card>

      {/* HidroAlly CTA */}
      {insights.cta && (
        <Card className="border-2 border-violet-200 bg-violet-50">
          <CardContent className="pt-6">
            <div className="flex flex-col items-center text-center gap-4">
              <p className="text-sm text-gray-700 leading-relaxed font-medium italic">
                {insights.cta}
              </p>
              <Button
                onClick={() => navigate('/hyper-ai')}
                className="bg-violet-600 hover:bg-violet-700 text-white rounded-xl px-8"
              >
                Continue in HidroAlly Chat
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default AIGeneratedInsights;
