import { BodyArea, Trigger, BodyAreaDetail } from "@/types";

export type TriggerCategory = "environmental" | "emotional" | "dietary" | "physical";

export interface TriggerOption {
  label: string;
  emoji: string;
  type: TriggerCategory;
  tip?: string;
  keywords: string[];
}

export interface BodyAreaOption extends BodyAreaDetail {
  emoji: string;
  clinicalName: string;
  complication: string;
  priority: "High" | "Medium";
  keywords: string[];
}

export const BODY_AREA_OPTIONS: BodyAreaOption[] = [
  {
    area: "face",
    name: "face",
    label: "Face",
    icon: "smile",
    emoji: "😰",
    clinicalName: "Craniofacial Hyperhidrosis",
    complication: "Visible sweating, social anxiety, skin irritation",
    priority: "High",
    keywords: ["face", "forehead", "cheeks"],
  },
  {
    area: "scalp",
    name: "scalp",
    label: "Scalp",
    icon: "brain",
    emoji: "🧢",
    clinicalName: "Craniofacial Hyperhidrosis",
    complication: "Wet hair, scalp odor, hair product interference",
    priority: "High",
    keywords: ["scalp", "head", "hair"],
  },
  {
    area: "face_scalp",
    name: "face_scalp",
    label: "Face & Scalp",
    icon: "smile",
    emoji: "😰",
    clinicalName: "Craniofacial Hyperhidrosis",
    complication: "Vision interference, makeup challenges, social withdrawal",
    priority: "High",
    keywords: ["face and scalp", "head and face"],
  },
  {
    area: "feet",
    name: "feet",
    label: "Feet",
    icon: "foot",
    emoji: "🦶",
    clinicalName: "Plantar Hyperhidrosis",
    complication: "Fungal infections, odor, shoe damage",
    priority: "High",
    keywords: ["feet", "foot"],
  },
  {
    area: "toes",
    name: "toes",
    label: "Toes",
    icon: "foot",
    emoji: "🦶",
    clinicalName: "Plantar Hyperhidrosis",
    complication: "Toe grip, moisture between toes, fungal risk",
    priority: "High",
    keywords: ["toes"],
  },
  {
    area: "soles",
    name: "soles",
    label: "Soles",
    icon: "foot",
    emoji: "🦶",
    clinicalName: "Plantar Hyperhidrosis",
    complication: "Slippery grip on floor, fungal risk, discomfort",
    priority: "High",
    keywords: ["soles"],
  },
  {
    area: "feet_soles",
    name: "feet_soles",
    label: "Feet & Soles",
    icon: "foot",
    emoji: "🦶",
    clinicalName: "Plantar Hyperhidrosis",
    complication: "Fungal infections, odor, shoe damage",
    priority: "High",
    keywords: ["feet and soles"],
  },
  {
    area: "palms",
    name: "palms",
    label: "Palms",
    icon: "hand",
    emoji: "🤚",
    clinicalName: "Palmar Hyperhidrosis",
    complication: "Touchscreen difficulty, slippery grip, social anxiety",
    priority: "High",
    keywords: ["palms"],
  },
  {
    area: "fingers",
    name: "fingers",
    label: "Fingers",
    icon: "hand",
    emoji: "🖐️",
    clinicalName: "Palmar Hyperhidrosis",
    complication: "Fine motor tasks, fingerprint sensors, social touch",
    priority: "High",
    keywords: ["fingers"],
  },
  {
    area: "hands",
    name: "hands",
    label: "Hands",
    icon: "hand",
    emoji: "🤚",
    clinicalName: "Palmar Hyperhidrosis",
    complication: "Shaking hands difficulty, social anxiety, grip issues",
    priority: "High",
    keywords: ["hands"],
  },
  {
    area: "underarms",
    name: "underarms",
    label: "Armpits",
    icon: "user",
    emoji: "💪",
    clinicalName: "Axillary Hyperhidrosis",
    complication: "Visible stains, skin irritation, bromhidrosis",
    priority: "High",
    keywords: ["underarms", "armpits", "pits"],
  },
  {
    area: "entire_body",
    name: "entire_body",
    label: "Entire Body",
    icon: "user",
    emoji: "👤",
    clinicalName: "Generalized Hyperhidrosis",
    complication: "Severe dehydration, multiple clothing changes, exhaustion",
    priority: "Medium",
    keywords: ["entire body", "everywhere", "all over"],
  },
  {
    area: "trunk",
    name: "trunk",
    label: "Trunk",
    icon: "shirt",
    emoji: "👕",
    clinicalName: "Truncal Hyperhidrosis",
    complication: "Clothing adherence, rapid dehydration, torso discomfort",
    priority: "Medium",
    keywords: ["trunk", "torso"],
  },
  {
    area: "chest",
    name: "chest",
    label: "Chest",
    icon: "heart",
    emoji: "🫀",
    clinicalName: "Truncal Hyperhidrosis",
    complication: "Frequent clothing changes, dehydration risk",
    priority: "Medium",
    keywords: ["chest"],
  },
  {
    area: "back",
    name: "back",
    label: "Back",
    icon: "body",
    emoji: "🔙",
    clinicalName: "Truncal Hyperhidrosis",
    complication: "Rapid dehydration, frequent clothing changes",
    priority: "Medium",
    keywords: ["back"],
  },
  {
    area: "groin",
    name: "groin",
    label: "Groin",
    icon: "user",
    emoji: "🩲",
    clinicalName: "Inguinal Hyperhidrosis",
    complication: "Jock itch, physical discomfort, intimate relationship stress",
    priority: "Medium",
    keywords: ["groin", "crotch"],
  },
];

export const TRIGGER_GROUPS: {
  category: TriggerCategory;
  title: string;
  categoryEmoji: string;
  researchNote: string;
  selectedBg: string;
  selectedBorder: string;
  triggers: TriggerOption[];
}[] = [
  {
    category: "environmental",
    title: "Environment & Situation",
    categoryEmoji: "🌡️",
    researchNote: "Physical + social environments combine to amplify sympathetic nervous system response",
    selectedBg: "bg-orange-50",
    selectedBorder: "border-orange-400",
    triggers: [
      {
        label: "Hot Temperature",
        emoji: "☀️",
        type: "environmental",
        tip: "Direct heat activates eccrine glands across the body",
        keywords: ["hot", "heat", "temperature", "warm"],
      },
      {
        label: "High Humidity",
        emoji: "🌫️",
        type: "environmental",
        tip: "Evaporative cooling fails in humid air, worsening sweating",
        keywords: ["humid", "humidity", "moist air"],
      },
      {
        label: "Crowded Spaces",
        emoji: "👥",
        type: "environmental",
        tip: "Combines ambient heat with social anxiety — a common hybrid trigger",
        keywords: ["crowded", "crowd", "lots of people"],
      },
      {
        label: "Bright Lights",
        emoji: "💡",
        type: "environmental",
        tip: "Sensory overstimulation can activate the sympathetic nervous system",
        keywords: ["bright lights", "bright", "glare"],
      },
      {
        label: "Loud Noises",
        emoji: "🔊",
        type: "environmental",
        tip: "Acoustic stress triggers CNS arousal and sweating response",
        keywords: ["loud", "noise", "noisy"],
      },
      {
        label: "Transitional Temperature",
        emoji: "🌡️",
        type: "environmental",
        tip: "Moving from AC to heat (or vice versa) rapidly can trigger an episode",
        keywords: ["changing temperature", "transition"],
      },
      {
        label: "Synthetic Fabrics",
        emoji: "👕",
        type: "environmental",
        tip: "Polyester and nylon trap heat and restrict evaporation",
        keywords: ["synthetic", "fabric", "polyester", "clothes"],
      },
      {
        label: "Outdoor Sun Exposure",
        emoji: "🏖️",
        type: "environmental",
        tip: "Radiant heat from sun exposure combined with UV stress",
        keywords: ["sun", "outside", "sunlight"],
      },
    ],
  },
  {
    category: "emotional",
    title: "Emotional & Cognitive",
    categoryEmoji: "🧠",
    researchNote: "Emotional triggers initiate the sympathetic 'fight or flight' response.",
    selectedBg: "bg-purple-50",
    selectedBorder: "border-purple-400",
    triggers: [
      {
        label: "Stress",
        emoji: "😫",
        type: "emotional",
        tip: "Chronic or acute stress directly activates the sympathetic nervous system",
        keywords: ["stress", "stressed"],
      },
      {
        label: "Anxiety",
        emoji: "😰",
        type: "emotional",
        tip: "Anxiety creates a hyperarousal state that activates eccrine glands",
        keywords: ["anxiety", "anxious", "nervous"],
      },
      {
        label: "Anticipatory Sweating",
        emoji: "💭",
        type: "emotional",
        tip: "Thinking about sweating triggers the episode you feared",
        keywords: ["thinking about sweating", "anticipating"],
      },
      {
        label: "Embarrassment",
        emoji: "😳",
        type: "emotional",
        tip: "Social shame activates the sympathetic nervous system immediately",
        keywords: ["embarrassment", "embarrassed", "shame"],
      },
      {
        label: "Excitement",
        emoji: "⚡",
        type: "emotional",
        tip: "Even positive excitement can trigger the same sympathetic pathway",
        keywords: ["excited", "excitement"],
      },
      {
        label: "Anger",
        emoji: "😤",
        type: "emotional",
        tip: "Emotional arousal elevates sympathetic tone and can trigger episodes",
        keywords: ["angry", "anger"],
      },
      {
        label: "Nervousness",
        emoji: "😬",
        type: "emotional",
        tip: "Low-grade chronic nervousness sustains sweating",
        keywords: ["nervousness"],
      },
      {
        label: "Public Speaking",
        emoji: "🎤",
        type: "emotional",
        tip: "Combines performance anxiety with social visibility",
        keywords: ["public speaking", "presentation", "speaking"],
      },
      {
        label: "Social Interaction",
        emoji: "🤝",
        type: "emotional",
        tip: "Handshakes, meetings, physical proximity",
        keywords: ["social", "meeting", "shaking hands"],
      },
      {
        label: "Work Pressure",
        emoji: "📋",
        type: "emotional",
        tip: "Deadline stress and professional performance anxiety",
        keywords: ["work", "deadline", "pressure"],
      },
      {
        label: "Exam / Test Situation",
        emoji: "📝",
        type: "emotional",
        tip: "High-stakes performance environments",
        keywords: ["exam", "test"],
      },
    ],
  },
  {
    category: "dietary",
    title: "Food, Drink & Gustatory",
    categoryEmoji: "🍽️",
    researchNote: "Gustatory sweating occurs when eating triggers sweating.",
    selectedBg: "bg-green-50",
    selectedBorder: "border-green-400",
    triggers: [
      {
        label: "Spicy Food",
        emoji: "🌶️",
        type: "dietary",
        tip: "Capsaicin stimulates trigeminal nerve",
        keywords: ["spicy", "chili", "hot food"],
      },
      {
        label: "Caffeine",
        emoji: "☕",
        type: "dietary",
        tip: "CNS stimulant — directly activates sympathetic nervous system",
        keywords: ["caffeine", "coffee", "tea", "energy drink"],
      },
      {
        label: "Alcohol",
        emoji: "🍷",
        type: "dietary",
        tip: "Causes vasodilation and body temperature spike",
        keywords: ["alcohol", "wine", "beer", "drink"],
      },
      {
        label: "Hot Drinks",
        emoji: "🍵",
        type: "dietary",
        tip: "Raises core body temperature regardless of content",
        keywords: ["hot drink", "tea", "coffee"],
      },
      {
        label: "Heavy Meals",
        emoji: "🍽️",
        type: "dietary",
        tip: "Postprandial thermogenesis — digesting large meals generates internal heat",
        keywords: ["heavy meal", "big meal", "eating a lot"],
      },
      {
        label: "Gustatory Sweating",
        emoji: "😋",
        type: "dietary",
        tip: "Sweating triggered by eating in general",
        keywords: ["eating", "food"],
      },
      {
        label: "Energy Drinks",
        emoji: "⚡",
        type: "dietary",
        tip: "High caffeine + stimulant combinations amplify sympathetic response",
        keywords: ["energy drink", "red bull", "monster"],
      },
    ],
  },
  {
    category: "physical",
    title: "Physical Activity & Body State",
    categoryEmoji: "🏃",
    researchNote: "Exercise-induced sweating is normal but can be disproportionate.",
    selectedBg: "bg-blue-50",
    selectedBorder: "border-blue-400",
    triggers: [
      {
        label: "Physical Exercise",
        emoji: "🏃",
        type: "physical",
        tip: "Exercise raises core body temperature",
        keywords: ["exercise", "running", "gym", "workout"],
      },
      {
        label: "Night Sweats",
        emoji: "🌙",
        type: "physical",
        tip: "Sweating during sleep may indicate secondary hyperhidrosis",
        keywords: ["night sweats", "sleeping", "woke up sweaty"],
      },
      {
        label: "Poor Sleep",
        emoji: "😴",
        type: "physical",
        tip: "Sleep deprivation heightens sympathetic nervous system sensitivity",
        keywords: ["poor sleep", "tired", "no sleep"],
      },
      {
        label: "Hormonal Changes",
        emoji: "🔄",
        type: "physical",
        keywords: ["hormones", "period", "menopause"],
      },
      {
        label: "Illness / Fever",
        emoji: "🤒",
        type: "physical",
        tip: "Systemic illness increases sweating as part of immune response",
        keywords: ["illness", "fever", "sick"],
      },
      {
        label: "Hypoglycemia",
        emoji: "🩸",
        type: "physical",
        tip: "Low blood sugar triggers compensatory sweating",
        keywords: ["low blood sugar", "hypoglycemia"],
      },
      {
        label: "Certain Clothing",
        emoji: "🧥",
        type: "physical",
        tip: "Non-breathable or tight clothing traps heat",
        keywords: ["clothing", "tight clothes"],
      },
    ],
  },
  {
    category: "physical",
    title: "Medications & Supplements",
    categoryEmoji: "💊",
    researchNote: "Pharmacological triggers are a major cause of secondary hyperhidrosis.",
    selectedBg: "bg-red-50",
    selectedBorder: "border-red-400",
    triggers: [
      {
        label: "SSRIs / Antidepressants",
        emoji: "💊",
        type: "physical",
        tip: "Serotonergic thermoregulatory disruption",
        keywords: ["medication", "pill", "ssri", "antidepressant"],
      },
      {
        label: "Opioids / Pain Medication",
        emoji: "💉",
        type: "physical",
        tip: "Opioids directly stimulate sweat glands through CNS pathways",
        keywords: ["pain killers", "opioids"],
      },
      {
        label: "NSAIDs (Aspirin, Ibuprofen)",
        emoji: "🩺",
        type: "physical",
        tip: "Common over-the-counter pain relievers with sweating as a side effect",
        keywords: ["aspirin", "ibuprofen", "nsaid"],
      },
      {
        label: "Blood Pressure Medication",
        emoji: "❤️",
        type: "physical",
        tip: "Beta-blockers and calcium channel blockers can cause hyperhidrosis",
        keywords: ["blood pressure meds"],
      },
      {
        label: "Insulin / Diabetes Medication",
        emoji: "🩸",
        type: "physical",
        tip: "Hypoglycemia episodes caused by insulin can trigger sweating",
        keywords: ["insulin", "diabetes medication"],
      },
      {
        label: "Supplements / Herbal",
        emoji: "🌿",
        type: "physical",
        tip: "Some herbal supplements affect thermoregulation",
        keywords: ["supplements", "herbal"],
      },
      {
        label: "New Medication",
        emoji: "🔔",
        type: "physical",
        tip: "Starting a new medication — sweating is a common adjustment side effect",
        keywords: ["new medication"],
      },
    ],
  },
];
