// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uimagdqtxuqpwupcvfws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpbWFnZHF0eHVxcHd1cGN2ZndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODU3MDcsImV4cCI6MjA2MzY2MTcwN30.xgw9bj3ZZIRAVpYD7kQOxxIij69jqIxHG-1f2lEXINI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);